# Generated by Django 3.2.9 on 2021-11-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=80, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_verification',
            field=models.CharField(default='123', max_length=256, verbose_name='Password verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=256, verbose_name='Password'),
        ),
    ]
